# SQLite version 3.x
#   gem install sqlite3
#   sudo apt-get install libmysql-ruby libmysqlclient-dev
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password: 22143521

development:
  <<: *defaults
  database: price_development

test:
  <<: *defaults
  database: price_test

production:
  <<: *defaults
  database: price_development
