# SQLite version 3.x
#   gem install sqlite3
#   sudo apt-get install libmysql-ruby libmysqlclient-dev
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
defaults: &defaults
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  timeout: 5000
  host:     <%= Settings[:db_master_host] %>
  database: <%= Rails.application.secrets[:mp_db_name] %>
  username: <%= Rails.application.secrets[:mp_db_user] %>
  password: <%= Rails.application.secrets[:mp_db_password] %>

development:
  <<: *defaults
  database: price_development

staging:
  <<: *defaults
  database: price_test

test:
  <<: *defaults
  database: price_test

production:
  <<: *defaults
  database: price_development
